spring.application.name=FinanceTracker
spring.docker.compose.enabled=false

spring.datasource.url=jdbc:postgresql://db.upuxnqepzvswlcmqviwd.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=haxtid-bitqa1-nykhiR

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=finance-tracker-jwt-secret-key-must-be-256bits-long!!
jwt.expiration-ms=86400000
